- hosts: localhost
  become: true
  pre_tasks:
    - name: update cache
      dnf:
        update_cache: true
      tags:
      - node
      - zsh
  tasks:
    - include_task: tasks/core-setups.yml
    - include_task: tasks/zsh.yml
    - include_task: tasks/node.yml
    - include_task: tasks/npm-pkgs.yml
    - include_task: tasks/git-setup.yml
    - include_task: tasks/aws.yml
    - include_task: tasks/neovim-setup.yml
