- name: Install AWS CLI v2
  become: true
  shell: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
    rm -rf awscliv2.zip aws
  args:
    creates: /usr/local/bin/aws
  tags:
    - install
    - aws
    - cli

- name: Verify AWS CLI Installation
  shell: aws --version
  register: aws_cli_version
  ignore_errors: true
  tags:
    - verify
    - aws
    - cli

